name: Deploy to Developer2 Sandbox
run-name: ${{ github.actor }} is running the Github Actions 🚀

on:
  pull_request:
    types: [closed]
    branches:
      - developer2
    paths:
      - 'force-app/**'

jobs:
  build-and-deploy: 
    name: Validate Dev
    uses: "./.github/workflows/templatedev2.yml"
    permissions:
      contents: read
      security-events: write
      actions: read
    with:
      environment: developer2
    secrets: inherit