name: Deploy to QA Sandbox
run-name: ${{ github.actor }} is running the Github Actions 🚀

on:
  pull_request:
    types: [closed]
    branches:
      - qa
    paths:
      - 'force-app/**'

jobs:
  build-and-deploy: 
    name: Deploy to QA
    uses: "./.github/workflows/templateqa.yml"
    permissions:
      contents: read
      security-events: write
      actions: read
    with:
      environment: QA
    secrets: inherit