name: Deploy to Developer Sandbox
run-name: ${{ github.actor }} is running the Github Actions 🚀

on:
  pull_request:
    types: [closed]
    branches:
      - developer
    paths:
      - 'force-app/**'

jobs:
  build-and-deploy: 
    name: Validate Dev
    uses: "./.github/workflows/template.yml"
    permissions:
      contents: read
      security-events: write
      actions: read
    with:
      environment: developer
    secrets: inherit