name: Validate to Production environment
run-name: ${{ github.actor }} is running the Github Actions 🚀

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - main
    paths:
      - 'force-app/**'

jobs:
  build-and-deploy: 
    name: Validate to Production
    uses: "./.github/workflows/templateprod.yml"
    permissions:
      contents: read
      security-events: write
      actions: read
    with:
      environment: Production
    secrets: inherit